# Generated by Django 5.2.10 on 2026-02-24 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('voice', '0008_alter_lovedone_core_memories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationsession',
            name='conversatio_profile_69ecbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversationsession',
            name='conversatio_started_151634_idx',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='title',
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['loved_one'], name='conversatio_loved_o_cbb108_idx'),
        ),
    ]
