# Generated by Django 5.2.10 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_conversationsession_conversatio_profile_69ecbf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='channel',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice')], db_index=True, default='chat', max_length=16),
        ),
    ]
