# Generated by Django 5.2.10 on 2026-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_usersubscription_subscriptiontalktimeusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='app_store_product_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='playstore_product_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
