# Generated by Django 5.2.10 on 2026-02-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LovedOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('relationship', models.CharField(blank=True, default='', max_length=128)),
                ('nickname_for_user', models.CharField(blank=True, default='', max_length=128)),
                ('speaking_style', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['profile_id', 'created_at'], name='voice_loved_profile_439769_idx')],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loved_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='voice.lovedone')),
            ],
            options={
                'indexes': [models.Index(fields=['loved_one', 'created_at'], name='voice_memor_loved_o_f4506a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice_samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loved_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_samples', to='voice.lovedone')),
            ],
            options={
                'indexes': [models.Index(fields=['loved_one', 'created_at'], name='voice_voice_loved_o_77f1ab_idx')],
            },
        ),
    ]
