# Generated by Django 5.2.10 on 2026-02-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='eleven_voice_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
