# Generated by Django 5.2.10 on 2026-02-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0005_lovedone_description_lovedone_last_conversation_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='core_memories',
            field=models.TextField(blank=True, default=''),
        ),
    ]
