# Generated by Django 5.2.10 on 2026-02-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0006_lovedone_core_memories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicesample',
            name='loved_one',
        ),
        migrations.AddField(
            model_name='lovedone',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_files/'),
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='VoiceSample',
        ),
    ]
