# Generated by Django 5.2.10 on 2026-02-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0007_remove_voicesample_loved_one_lovedone_voice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovedone',
            name='core_memories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='eleven_voice_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='nickname_for_user',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='relationship',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='speaking_style',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
