# Generated by Django 5.2.10 on 2026-05-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0008_alter_lovedone_core_memories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('global', 'Global'), ('personal', 'Personal')], default='global', max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loved_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='voice.lovedone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quote_type', 'created_at'], name='voice_quote_quote_t_a70095_idx'), models.Index(fields=['user', 'quote_type'], name='voice_quote_user_id_a0f83e_idx'), models.Index(fields=['loved_one', 'quote_type'], name='voice_quote_loved_o_5289fb_idx')],
            },
        ),
    ]
