# Generated by Django 5.2.10 on 2026-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0009_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
